In [1]:
import pandas as pd
import json

In [35]:
dataFile_US_Econ = "Resources/us_econ_growth.csv"
econ_growth_df = pd.read_csv(dataFile_US_Econ)
econ_growth_df = econ_growth_df.set_index("Year")
econ_growth_df = econ_growth_df.rename(columns={"Value": "annual_gnp_growth_pct"})
econ_growth_df.head()

           Date annual_gnp_growth_pct
Year
2018  30-Sep-18                 3.04%
2017  31-Dec-17                 2.47%
2016  31-Dec-16                 1.88%
2015  31-Dec-15                 2.00%
2014  31-Dec-14                 2.70%

In [18]:
cig_file = "Resources/sales-of-cigarettes-per-adult-per-day.csv"
cig_df = pd.read_csv(cig_file)
cig_df = cig_df.set_index("Year")
cig_df.head()

,Entity,Code,Sales of cigarettes per adult per day (International Smoking Statistics (2017)) (cigarettes)
Year,,,
1988,Armenia,ARM,12.0
1989,Armenia,ARM,11.6
1990,Armenia,ARM,11.9
1991,Armenia,ARM,9.3
1992,Armenia,ARM,4.9

In [14]:
with open('Resources/presidents_debt.json') as json_data:
    cig_data = json.load(json_data)
    #print(cig_data)
    
print(json.dumps(cig_data, indent=4, sort_keys=True))

{
    "data": {
        "by_president": [
            {
                "age": 88,
                "date_born_epoch": -2702833200,
                "date_died_epoch": 94197600,
                "name": "Harry S. Truman",
                "number": 33,
                "party": "Democratic",
                "term_debt_increase_pct": 28.9,
                "term_end_epoch": -534794400,
                "term_start_epoch": -780174000
            },
            {
                "age": 78,
                "date_born_epoch": -2499793200,
                "date_died_epoch": -24087600,
                "name": "Dwight D. Eisenhower",
                "number": 34,
                "party": "Republican",
                "term_debt_increase_pct": 10.5,
                "term_end_epoch": -282333600,
                "term_start_epoch": -534794400
            },
            {
                "age": 46,
                "date_born_epoch": -1659726000,
                "date_died_epoch": -192823200,
                "name": "John F. Kennedy",
                "number": 35,
                "party": "Democratic",
                "term_debt_increase_pct": 6.8,
                "term_end_epoch": -192823200,
                "term_start_epoch": -282333600
            },
            {
                "age": 64,
                "date_born_epoch": -1935946800,
                "date_died_epoch": 96530400,
                "name": "Lyndon B. Johnson",
                "number": 36,
                "party": "Democratic",
                "term_debt_increase_pct": 13.6,
                "term_end_epoch": -29872800,
                "term_start_epoch": -192823200
            },
            {
                "age": 81,
                "date_born_epoch": -1798048800,
                "date_died_epoch": 766990800,
                "name": "Richard Nixon",
                "number": 37,
                "party": "Republican",
                "term_debt_increase_pct": 31.8,
                "term_end_epoch": 145256400,
                "term_start_epoch": -29872800
            },
            {
                "age": 93,
                "date_born_epoch": -1781982000,
                "date_died_epoch": 1167112800,
                "name": "Gerald Ford",
                "number": 38,
                "party": "Republican",
                "term_debt_increase_pct": 35.4,
                "term_end_epoch": 222588000,
                "term_start_epoch": 145256400
            },
            {
                "age": 91,
                "date_born_epoch": 1001912400,
                "date_died_epoch": -33008580000,
                "name": "Jimmy Carter",
                "number": 39,
                "party": "Democratic",
                "term_debt_increase_pct": 46.3,
                "term_end_epoch": 348818400,
                "term_start_epoch": 222588000
            },
            {
                "age": 93,
                "date_born_epoch": -1858788000,
                "date_died_epoch": 1086411600,
                "name": "Ronald Reagan",
                "number": 40,
                "party": "Republican",
                "term_debt_increase_pct": 186.7,
                "term_end_epoch": 601279200,
                "term_start_epoch": 348818400
            },
            {
                "age": 91,
                "date_born_epoch": -1437591600,
                "date_died_epoch": null,
                "name": "George H. W. Bush",
                "number": 41,
                "party": "Republican",
                "term_debt_increase_pct": 56.2,
                "term_end_epoch": 727509600,
                "term_start_epoch": 601279200
            },
            {
                "age": 69,
                "date_born_epoch": -737492400,
                "date_died_epoch": null,
                "name": "Bill Clinton",
                "number": 42,
                "party": "Democratic",
                "term_debt_increase_pct": 39.6,
                "term_end_epoch": 979970400,
                "term_start_epoch": 727509600
            },
            {
                "age": 69,
                "date_born_epoch": -741294000,
                "date_died_epoch": null,
                "name": "George W. Bush",
                "number": 43,
                "party": "Republican",
                "term_debt_increase_pct": 76.7,
                "term_end_epoch": 1232431200,
                "term_start_epoch": 979970400
            },
            {
                "age": 54,
                "date_born_epoch": -265402800,
                "date_died_epoch": null,
                "name": "Barack Obama",
                "number": 44,
                "party": "Democratic",
                "term_debt_increase_pct": 87.8,
                "term_end_epoch": 1484892000,
                "term_start_epoch": 1232431200
            }
        ],
        "by_year": [
            {
                "annual_debt_increase_pct": 0.2,
                "party": "Democratic",
                "president": "Harry S. Truman",
                "year": 1949
            },
            {
                "annual_debt_increase_pct": 1.8,
                "party": "Democratic",
                "president": "Harry S. Truman",
                "year": 1950
            },
            {
                "annual_debt_increase_pct": -0.8,
                "party": "Democratic",
                "president": "Harry S. Truman",
                "year": 1951
            },
            {
                "annual_debt_increase_pct": 1.5,
                "party": "Democratic",
                "president": "Harry S. Truman",
                "year": 1952
            },
            {
                "annual_debt_increase_pct": 2.7,
                "party": "Republican",
                "president": "Dwight D. Eisenhower",
                "year": 1953
            },
            {
                "annual_debt_increase_pct": 2.0,
                "party": "Republican",
                "president": "Dwight D. Eisenhower",
                "year": 1954
            },
            {
                "annual_debt_increase_pct": 1.1,
                "party": "Republican",
                "president": "Dwight D. Eisenhower",
                "year": 1955
            },
            {
                "annual_debt_increase_pct": -0.6,
                "party": "Republican",
                "president": "Dwight D. Eisenhower",
                "year": 1956
            },
            {
                "annual_debt_increase_pct": -0.8,
                "party": "Republican",
                "president": "Dwight D. Eisenhower",
                "year": 1957
            },
            {
                "annual_debt_increase_pct": 2.1,
                "party": "Republican",
                "president": "Dwight D. Eisenhower",
                "year": 1958
            },
            {
                "annual_debt_increase_pct": 3.0,
                "party": "Republican",
                "president": "Dwight D. Eisenhower",
                "year": 1959
            },
            {
                "annual_debt_increase_pct": 0.6,
                "party": "Republican",
                "president": "Dwight D. Eisenhower",
                "year": 1960
            },
            {
                "annual_debt_increase_pct": 0.9,
                "party": "Democratic",
                "president": "John F. Kennedy",
                "year": 1961
            },
            {
                "annual_debt_increase_pct": 3.2,
                "party": "Democratic",
                "president": "John F. Kennedy",
                "year": 1962
            },
            {
                "annual_debt_increase_pct": 2.6,
                "party": "Democratic",
                "president": "John F. Kennedy",
                "year": 1963
            },
            {
                "annual_debt_increase_pct": 1.9,
                "party": "Democratic",
                "president": "Lyndon B. Johnson",
                "year": 1964
            },
            {
                "annual_debt_increase_pct": 1.8,
                "party": "Democratic",
                "president": "Lyndon B. Johnson",
                "year": 1965
            },
            {
                "annual_debt_increase_pct": 0.8,
                "party": "Democratic",
                "president": "Lyndon B. Johnson",
                "year": 1966
            },
            {
                "annual_debt_increase_pct": 2.0,
                "party": "Democratic",
                "president": "Lyndon B. Johnson",
                "year": 1967
            },
            {
                "annual_debt_increase_pct": 6.5,
                "party": "Democratic",
                "president": "Lyndon B. Johnson",
                "year": 1968
            },
            {
                "annual_debt_increase_pct": 1.8,
                "party": "Republican",
                "president": "Richard Nixon",
                "year": 1969
            },
            {
                "annual_debt_increase_pct": 4.9,
                "party": "Republican",
                "president": "Richard Nixon",
                "year": 1970
            },
            {
                "annual_debt_increase_pct": 7.3,
                "party": "Republican",
                "president": "Richard Nixon",
                "year": 1971
            },
            {
                "annual_debt_increase_pct": 7.3,
                "party": "Republican",
                "president": "Richard Nixon",
                "year": 1972
            },
            {
                "annual_debt_increase_pct": 7.2,
                "party": "Republican",
                "president": "Richard Nixon",
                "year": 1973
            },
            {
                "annual_debt_increase_pct": 3.7,
                "party": "Republican",
                "president": "Gerald Ford",
                "year": 1974
            },
            {
                "annual_debt_increase_pct": 12.2,
                "party": "Republican",
                "president": "Gerald Ford",
                "year": 1975
            },
            {
                "annual_debt_increase_pct": 16.4,
                "party": "Republican",
                "president": "Gerald Ford",
                "year": 1976
            },
            {
                "annual_debt_increase_pct": 12.6,
                "party": "Democratic",
                "president": "Jimmy Carter",
                "year": 1977
            },
            {
                "annual_debt_increase_pct": 10.4,
                "party": "Democratic",
                "president": "Jimmy Carter",
                "year": 1978
            },
            {
                "annual_debt_increase_pct": 7.1,
                "party": "Democratic",
                "president": "Jimmy Carter",
                "year": 1979
            },
            {
                "annual_debt_increase_pct": 9.8,
                "party": "Democratic",
                "president": "Jimmy Carter",
                "year": 1980
            },
            {
                "annual_debt_increase_pct": 9.9,
                "party": "Republican",
                "president": "Ronald Reagan",
                "year": 1981
            },
            {
                "annual_debt_increase_pct": 14.4,
                "party": "Republican",
                "president": "Ronald Reagan",
                "year": 1982
            },
            {
                "annual_debt_increase_pct": 20.6,
                "party": "Republican",
                "president": "Ronald Reagan",
                "year": 1983
            },
            {
                "annual_debt_increase_pct": 14.2,
                "party": "Republican",
                "president": "Ronald Reagan",
                "year": 1984
            },
            {
                "annual_debt_increase_pct": 16.0,
                "party": "Republican",
                "president": "Ronald Reagan",
                "year": 1985
            },
            {
                "annual_debt_increase_pct": 16.6,
                "party": "Republican",
                "president": "Ronald Reagan",
                "year": 1986
            },
            {
                "annual_debt_increase_pct": 10.6,
                "party": "Republican",
                "president": "Ronald Reagan",
                "year": 1987
            },
            {
                "annual_debt_increase_pct": 10.7,
                "party": "Republican",
                "president": "Ronald Reagan",
                "year": 1988
            },
            {
                "annual_debt_increase_pct": 9.8,
                "party": "Republican",
                "president": "George H. W. Bush",
                "year": 1989
            },
            {
                "annual_debt_increase_pct": 13.2,
                "party": "Republican",
                "president": "George H. W. Bush",
                "year": 1990
            },
            {
                "annual_debt_increase_pct": 13.4,
                "party": "Republican",
                "president": "George H. W. Bush",
                "year": 1991
            },
            {
                "annual_debt_increase_pct": 10.9,
                "party": "Republican",
                "president": "George H. W. Bush",
                "year": 1992
            },
            {
                "annual_debt_increase_pct": 8.5,
                "party": "Democratic",
                "president": "Bill Clinton",
                "year": 1993
            },
            {
                "annual_debt_increase_pct": 6.4,
                "party": "Democratic",
                "president": "Bill Clinton",
                "year": 1994
            },
            {
                "annual_debt_increase_pct": 6.0,
                "party": "Democratic",
                "president": "Bill Clinton",
                "year": 1995
            },
            {
                "annual_debt_increase_pct": 5.0,
                "party": "Democratic",
                "president": "Bill Clinton",
                "year": 1996
            },
            {
                "annual_debt_increase_pct": 3.6,
                "party": "Democratic",
                "president": "Bill Clinton",
                "year": 1997
            },
            {
                "annual_debt_increase_pct": 2.1,
                "party": "Democratic",
                "president": "Bill Clinton",
                "year": 1998
            },
            {
                "annual_debt_increase_pct": 2.4,
                "party": "Democratic",
                "president": "Bill Clinton",
                "year": 1999
            },
            {
                "annual_debt_increase_pct": 0.3,
                "party": "Democratic",
                "president": "Bill Clinton",
                "year": 2000
            },
            {
                "annual_debt_increase_pct": 2.3,
                "party": "Republican",
                "president": "George W. Bush",
                "year": 2001
            },
            {
                "annual_debt_increase_pct": 7.2,
                "party": "Republican",
                "president": "George W. Bush",
                "year": 2002
            },
            {
                "annual_debt_increase_pct": 8.9,
                "party": "Republican",
                "president": "George W. Bush",
                "year": 2003
            },
            {
                "annual_debt_increase_pct": 8.8,
                "party": "Republican",
                "president": "George W. Bush",
                "year": 2004
            },
            {
                "annual_debt_increase_pct": 7.5,
                "party": "Republican",
                "president": "George W. Bush",
                "year": 2005
            },
            {
                "annual_debt_increase_pct": 7.2,
                "party": "Republican",
                "president": "George W. Bush",
                "year": 2006
            },
            {
                "annual_debt_increase_pct": 5.9,
                "party": "Republican",
                "president": "George W. Bush",
                "year": 2007
            },
            {
                "annual_debt_increase_pct": 11.3,
                "party": "Republican",
                "president": "George W. Bush",
                "year": 2008
            },
            {
                "annual_debt_increase_pct": 18.8,
                "party": "Democratic",
                "president": "Barack Obama",
                "year": 2009
            },
            {
                "annual_debt_increase_pct": 13.9,
                "party": "Democratic",
                "president": "Barack Obama",
                "year": 2010
            },
            {
                "annual_debt_increase_pct": 9.1,
                "party": "Democratic",
                "president": "Barack Obama",
                "year": 2011
            },
            {
                "annual_debt_increase_pct": 8.6,
                "party": "Democratic",
                "president": "Barack Obama",
                "year": 2012
            },
            {
                "annual_debt_increase_pct": 4.2,
                "party": "Democratic",
                "president": "Barack Obama",
                "year": 2013
            },
            {
                "annual_debt_increase_pct": 6.5,
                "party": "Democratic",
                "president": "Barack Obama",
                "year": 2014
            },
            {
                "annual_debt_increase_pct": 1.8,
                "party": "Democratic",
                "president": "Barack Obama",
                "year": 2015
            },
            {
                "annual_debt_increase_pct": 3.7,
                "party": "Democratic",
                "president": "Barack Obama",
                "year": 2016
            }
        ]
    },
    "source": [
        "https://www.whitehouse.gov/omb/budget/Historicals"
    ]
}

In [25]:
year_data = cig_data["data"]["by_year"]
year_data = pd.DataFrame(year_data)
year_data = year_data.rename(columns={"year": "Year"})
year_data.head()

   annual_debt_increase_pct       party             president  Year
0                       0.2  Democratic       Harry S. Truman  1949
1                       1.8  Democratic       Harry S. Truman  1950
2                      -0.8  Democratic       Harry S. Truman  1951
3                       1.5  Democratic       Harry S. Truman  1952
4                       2.7  Republican  Dwight D. Eisenhower  1953

In [27]:
pres_year = year_data.set_index("Year")
pres_year.head()

      annual_debt_increase_pct       party             president
Year
1949                       0.2  Democratic       Harry S. Truman
1950                       1.8  Democratic       Harry S. Truman
1951                      -0.8  Democratic       Harry S. Truman
1952                       1.5  Democratic       Harry S. Truman
1953                       2.7  Republican  Dwight D. Eisenhower

In [37]:
pres_econ = pd.merge(pres_year, econ_growth_df, on='Year')
pres_econ = pres_econ[["president", "party", "annual_gnp_growth_pct", "annual_debt_increase_pct"]]
pres_econ.head()

,president,party,annual_gnp_growth_pct,annual_debt_increase_pct
Year,,,,
1949,Harry S. Truman,Democratic,-1.53%,0.2
1950,Harry S. Truman,Democratic,13.37%,1.8
1951,Harry S. Truman,Democratic,5.47%,-0.8
1952,Harry S. Truman,Democratic,5.37%,1.5
1953,Dwight D. Eisenhower,Republican,0.52%,2.7

In [126]:
ufo_file = "Resources/ufo.csv"
ufo_df = pd.read_csv(ufo_file)
ufo_df.head()

/anaconda3/envs/gwarl/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (5,9) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,datetime,city,state,country,shape,duration (seconds),duration (hours/min),comments,date posted,latitude,longitude
0,10/10/1949 20:30,san marcos,tx,us,cylinder,2700,45 minutes,This event took place in early fall around 194...,4/27/2004,29.8830556,-97.941111
1,10/10/1949 21:00,lackland afb,tx,NaN,light,7200,1-2 hrs,1949 Lackland AFB&#44 TX. Lights racing acros...,12/16/2005,29.38421,-98.581082
2,10/10/1955 17:00,chester (uk/england),NaN,gb,circle,20,20 seconds,Green/Orange circular disc over Chester&#44 En...,1/21/2008,53.2,-2.916667
3,10/10/1956 21:00,edna,tx,us,circle,20,1/2 hour,My older brother and twin sister were leaving ...,1/17/2004,28.9783333,-96.645833
4,10/10/1960 20:00,kaneohe,hi,us,light,900,15 minutes,AS a Marine 1st Lt. flying an FJ4B fighter/att...,1/22/2004,21.4180556,-157.803611

In [127]:
yeartime = ufo_df['datetime'].str.split('/', n=3, expand = True) 
year = yeartime[2].str.split(' ', n=0, expand = True) 
year = year[0]
year = year.astype(int)
year.head()

0    1949
1    1949
2    1955
3    1956
4    1960
Name: 0, dtype: int64

In [128]:
ufo_df['Year'] = year
ufo_df = ufo_df[ufo_df['country'] == 'us']
ufo_df_group = ufo_df.groupby(['Year']).agg(['count'])
ufo_df_group.head()

,datetime,city,state,country,shape,duration (seconds),duration (hours/min),comments,date posted,latitude,longitude
,count,count,count,count,count,count,count,count,count,count,count
Year,,,,,,,,,,,
1910,2,2,2,2,2,2,2,2,2,2,2
1920,1,1,1,1,1,1,1,1,1,1,1
1925,1,1,1,1,1,1,1,1,1,1,1
1929,1,1,1,1,1,1,1,1,1,1,1
1931,2,2,2,2,2,2,2,2,2,2,2

In [129]:
ufo_df_group = ufo_df_group['datetime']

In [130]:
ufo_df_group = ufo_df_group.rename(columns={'count':'ufo_sightings'})
ufo_df_group = pd.DataFrame(ufo_df_group)
ufo_df_group

      ufo_sightings
Year
1910              2
1920              1
1925              1
1929              1
1931              2
1934              1
1936              1
1937              2
1939              3
1941              1
1942              2
1943              1
1944              3
1945              7
1946              8
1947             33
1948              7
1949             15
1950             21
1951             13
1952             37
1953             26
1954             38
1955             25
1956             39
1957             62
1958             42
1959             43
1960             51
1961             41
...             ...
1985            171
1986            153
1987            176
1988            188
1989            200
1990            191
1991            180
1992            183
1993            228
1994            324
1995            915
1996            646
1997           1009
1998           1404
1999           2253
2000           2184
2001           2445
2002           2439
2003           2958
2004           3244
2005           3228
2006           2884
2007           3470
2008           4017
2009           3677
2010           3548
2011           4379
2012           6320
2013           6056
2014           1964

[83 rows x 1 columns]

In [131]:
pres_econ_ufo = pd.merge(pres_econ, ufo_df_group, on='Year')
pres_econ_ufo

,president,party,annual_gnp_growth_pct,annual_debt_increase_pct,ufo_sightings
Year,,,,,
1949,Harry S. Truman,Democratic,-1.53%,0.2,15
1950,Harry S. Truman,Democratic,13.37%,1.8,21
1951,Harry S. Truman,Democratic,5.47%,-0.8,13
1952,Harry S. Truman,Democratic,5.37%,1.5,37
1953,Dwight D. Eisenhower,Republican,0.52%,2.7,26
1954,Dwight D. Eisenhower,Republican,2.73%,2.0,38
1955,Dwight D. Eisenhower,Republican,6.58%,1.1,25
1956,Dwight D. Eisenhower,Republican,2.00%,-0.6,39
1957,Dwight D. Eisenhower,Republican,0.35%,-0.8,62
1958,Dwight D. Eisenhower,Republican,2.66%,2.1,42
1959,Dwight D. Eisenhower,Republican,4.59%,3.0,43
1960,Dwight D. Eisenhower,Republican,0.88%,0.6,51
1961,John F. Kennedy,Democratic,6.40%,0.9,41
1962,John F. Kennedy,Democratic,4.31%,3.2,56
1963,John F. Kennedy,Democratic,5.16%,2.6,68
1964,Lyndon B. Johnson,Democratic,5.16%,1.9,78
1965,Lyndon B. Johnson,Democratic,8.46%,1.8,164
1966,Lyndon B. Johnson,Democratic,4.50%,0.8,160
1967,Lyndon B. Johnson,Democratic,2.67%,2.0,147
1968,Lyndon B. Johnson,Democratic,4.96%,6.5,175
1969,Richard Nixon,Republican,2.05%,1.8,120
1970,Richard Nixon,Republican,-0.17%,4.9,109
1971,Richard Nixon,Republican,4.37%,7.3,97
1972,Richard Nixon,Republican,6.90%,7.3,119
1973,Richard Nixon,Republican,4.02%,7.2,188
1974,Gerald Ford,Republican,-1.95%,3.7,219
1975,Gerald Ford,Republican,2.55%,12.2,247
1976,Gerald Ford,Republican,4.31%,16.4,222
1977,Jimmy Carter,Democratic,5.01%,12.6,206
1978,Jimmy Carter,Democratic,6.66%,10.4,258
...,...,...,...,...,...
1985,Ronald Reagan,Republican,4.18%,16.0,171
1986,Ronald Reagan,Republican,2.91%,16.6,153
1987,Ronald Reagan,Republican,4.48%,10.6,176
1988,Ronald Reagan,Republican,3.80%,10.7,188
1989,George H. W. Bush,Republican,2.74%,9.8,200
1990,George H. W. Bush,Republican,0.60%,13.2,191
1991,George H. W. Bush,Republican,1.17%,13.4,180
1992,George H. W. Bush,Republican,4.38%,10.9,183
1993,Bill Clinton,Democratic,2.61%,8.5,228
1994,Bill Clinton,Democratic,4.12%,6.4,324
1995,Bill Clinton,Democratic,2.20%,6.0,915
1996,Bill Clinton,Democratic,4.42%,5.0,646
1997,Bill Clinton,Democratic,4.49%,3.6,1009
1998,Bill Clinton,Democratic,4.88%,2.1,1404
1999,Bill Clinton,Democratic,4.81%,2.4,2253
2000,Bill Clinton,Democratic,2.97%,0.3,2184
2001,George W. Bush,Republican,0.15%,2.3,2445
2002,George W. Bush,Republican,2.09%,7.2,2439
2003,George W. Bush,Republican,4.33%,8.9,2958
2004,George W. Bush,Republican,3.28%,8.8,3244
2005,George W. Bush,Republican,3.13%,7.5,3228
2006,George W. Bush,Republican,2.59%,7.2,2884
2007,George W. Bush,Republican,1.97%,5.9,3470
2008,George W. Bush,Republican,-2.75%,11.3,4017
2009,Barack Obama,Democratic,0.18%,18.8,3677
2010,Barack Obama,Democratic,2.57%,13.9,3548
2011,Barack Obama,Democratic,1.61%,9.1,4379
2012,Barack Obama,Democratic,1.47%,8.6,6320
2013,Barack Obama,Democratic,2.61%,4.2,6056
2014,Barack Obama,Democratic,2.70%,6.5,1964